### ISSUE TITLE
I can not get the value of DateTimePicker

### ISSUE THREAD

**Issue by victorbrugnolo** [gerhat/material-ui-formik-components#13]
I can not get the value of DateTimePicker, I set the name, but it is not passed to JSON in values

**Comment by gerhat** [comment]
Can please give an example?

**Comment by victorbrugnolo** [comment]
https://gist.github.com/victorbrugnolo/b58a66e1748c52a176cf6b215e654535

**Comment by gerhat** [comment]
Hi @victorbrugnolo 

you need to remove `value` and `onChange` props from datetime field since state is taken care by formik. See below:

```javascript
<Field name="datetime" component={DateTimePicker} />
````

And here is a working codesandbox of your gist:
https://codesandbox.io/embed/unruffled-mestorf-90l64
