### ISSUE TITLE
FieldArray does not render chipinput

### ISSUE THREAD

**Issue by giq-re** [gerhat/material-ui-formik-components#17]
**Issue:**
The chipinput works great when it is used as a standalone field but once you nest it in the field array component of formik the values never are set in the formik state.  i think because the field array uses dot notation to slice the initial values so that it can set values that are deeply nested  it is not translating properly with the components set field value method of transfering state.  a similar occurrence is happening with the switch component as when you change the initial state it says you are switching from an uncontrolled to a controlled component - i have not checked it yet but I bet that setFieldValue is being used in this case as well.   I can't seem to get a handle on it as of yet and was hoping someone who may have experienced this previously may have found a workaround.  Its almost like you will have to use the same method that they implement behind fieldArray so that when you set the value its being set as if you are setting it directly on the field prop versus the form prop. because it does work on the Select and Textinputs components.  i am rambling now because it just got me thinking.  

**_CodeSandBox:_**
i modified a codesandbox so you can see that the component works fine as long as its not within the fieldarray component. 

[![Edit Material-UI Formik Chip Input Field Array](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-ui-formik-chip-input-field-array-djqvi?fontsize=14)

**Comment by chaitanya1019** [comment]
I'm also facing the same issue. Please share workaround or release a fix ASAP

**Comment by giq-re** [comment]
I am happy to try to help. curious to see what the fix is because i tried to implement a few solutions with no success.

**Comment by gerhat** [comment]
Thanks for your input @chaitanya1019 @giq-re. An update is coming soon!

**Comment by gerhat** [comment]
@chaitanya1019, @giq-re can you please check v0.5.0 ?

**Comment by giq-re** [comment]
sure. just saw this. get back to you tomorrow.

**Comment by giq-re** [comment]
it is working. still get the uncontrolled warning for the switch. 

what are your plans for the the library with formik 2.0 out and everything being rewritten in hooks? deprecation of the Field prop...etc. it seems like the transition from class based components to hooks is really accelerating fast.

**Comment by gerhat** [comment]
@giq-re can you please open a new issue for the switch uncontrolled warning?

The plan is to keep supporting upcoming versions from both formik and material-ui.

**Comment by giq-re** [comment]
Yep. I will today.
