### ISSUE TITLE
Feature Request - Date Picker

### ISSUE THREAD

**Issue by owlyowl** [gerhat/material-ui-formik-components#19]
Hi,
Thanks for an awesome library. I was wondering if you were planning on implementing a DatePicker component any time soon?

**Comment by gerhat** [comment]
Thanks for your kind words.
It has already been implemented.
You need to install **Material-UI pickers** https://material-ui-pickers.dev/getting-started/installation

You can also check this example: https://github.com/gerhat/material-ui-formik-components/blob/master/example/src/SimpleFormExample.jsx

**Comment by owlyowl** [comment]
Thank you for your reply. I can see date time picker is implemented but not
date only without time..

**Comment by gerhat** [comment]
Totally right. I will implement it.

**Comment by owlyowl** [comment]
Thanks very much!

**Comment by gerhat** [comment]
@owlyowl can you please check v0.5.1 ? Thanks.
