### ISSUE TITLE
filterSelectedOptions for Autocomplete

### ISSUE THREAD

**Issue by pzapo** [gerhat/material-ui-formik-components#26]
Is there a way to use filterSelectedOptions for AutoComplete Component?
This option is would be very usable to pass to component.

**Comment by gerhat** [comment]
Yes. Here is an example:

```jsx
<Field
  name="country"
  options={countries}
  component={Autocomplete}
  filterSelectedOptions
/>
```

**Comment by pzapo** [comment]
Hi, i have checked that and i am afraid it doesn't work. 
Sample Code, more or less the same like in provided samples in repository.

```javascript
<Field
 name="category"
 multiple
 options={[{ label: "DK" }, { label: "NO" }, { label: "SV" }]}
 textFieldProps={{
    label: "Categories",
    required: true,
    variant: "outlined",
}}
component={Autocomplete}
filterSelectedOptions
/>
```
I am still able to select already selected option and make duplicates.
![Screenshot 2020-04-09 at 13 02 14](https://user-images.githubusercontent.com/31630544/78888641-56ced280-7a62-11ea-8593-6910e3021cf1.png)

I have also found that, i receive following warning:
`react_devtools_backend.js:6 Material-UI: the value provided to Autocomplete is invalid.
None of the options match with [{"value":1,"label":"DK"},{"value":1,"label":"DK"}].`

Could you point me where i am making mistake?
