### ISSUE TITLE
Null InitialValues doesn't work on AutoComplete with multiple option

### ISSUE THREAD

**Issue by JbPons** [gerhat/material-ui-formik-components#31]
This issue is related to a previous fixed issue : #28 

Now, with the last version of the Library I can't use autoComplete with multiple option without initialValue.

So I try to do: `skills: null` and `skills: [null]` I have a react error,.

After that I try in another way:  `skills: [{ label: '', value: ''}]`
This time it's work but I have an empty selected options.

You can find a working example here : https://codesandbox.io/s/nifty-turing-36dvv

**Comment by viperz0r** [comment]
Hi, 

I tested your example with skills being an empty array and didn´t get any error:

`const initialValues = {
  username: "",
  gender: "",
  country: "",
  skills: [],
  birthdate: null
};`

Does it solve your problem?

**Comment by JbPons** [comment]
Hello,

Yes it's solve my problem, Thanks.

But I think the library need to be update to handle the case I described in my previous commentary.

So, I don't close the issue to wait any update from the contributor.

**Comment by gerhat** [comment]
Hello. Thank you both for your comments.

I agree with @JbPons. `null` initial value should be handled properly.
Version 0.6.3 prints an error message in the console when the value is `null` and does not render the field.

<img width="592" alt="initial_value_null_error" src="https://user-images.githubusercontent.com/11447903/80856385-4e794a00-8c52-11ea-913d-602c70a8a46e.png">
