### ISSUE TITLE
Add optional dependencies to package.json

### ISSUE THREAD

**Issue by depiction** [gerhat/material-ui-formik-components#33]
The documentation says that the following packages are optional:

- Material-UI Lab >4.0 - used by Autocomplete
- Material-UI Pickers >= 3.0 - used by DatePicker, DateTimePicker, KeyboardDatePicker,KeyboardTimePicker, KeyboardDateTimePicker and TimePicker
- material-ui-chip-input >= 1.0 - used by ChipInput

However, in `package.json`, the above packages are listed in peerDependencies. If they are optional, they should be listed in optionalDependencies.(https://docs.npmjs.com/files/package.json#optionaldependencies)

**Comment by gerhat** [comment]
@depiction you are totally right. I didn't know `optionalDependencies` existed. Thank you for letting me know. Version 0.7.1 contains this change.
