### ISSUE TITLE
Unable to handle onChange on autocomplate

### ISSUE THREAD

**Issue by santhoshgudla** [gerhat/material-ui-formik-components#34]
Hi

I have 2 autocomplate text fields one with single selection and other with multiselection.
When user select a value in 1st textfield then I want to call api with selected value and populate values in the multiselection textfield.

But here I am unable to get the onChange in the 1st textfield.

Can you please suggest me the solution.

Thank you

**Comment by icrustandi** [comment]
This is because passing in a custom onChange to the textFieldProps isn't currently allowed:
https://github.com/gerhat/material-ui-formik-components/blob/master/src/Autocomplete/Autocomplete.d.ts

I can try to make a pr for this
