### ISSUE TITLE
Form doesn't submit/validate if fields are untouched

### ISSUE THREAD

**Issue by plnichols** [gerhat/material-ui-formik-components#4]
Hi, I noticed that in your example [RegistrationForm.jsx](https://github.com/gerhat/material-ui-formik-components/blob/master/example/src/RegistrationForm.jsx), if you don't touch/type anything in the form and try to submit, nothing happens.

There's no feedback at all to the user.

Then if you type 1 character in any field, the whole form gets validated with all fields in red (error).  

Maybe that's expected behaviour, but giving no feedback at all to the user doesn't seem to be the best way to go.  Is there a way to trigger the form validation even if the form was not touched?

**Comment by gerhat** [comment]
Hi @plnichols. This is the intended behaviour. The reasoning behind it is: "_Why show any errors if the nothing is changed in the form_". 

A workaround for now would be to have the submit button **disabled** while the form is not `dirty`.
See updated example: https://github.com/gerhat/material-ui-formik-components/blob/master/example/src/RegistrationForm.jsx

**Comment by pzapo** [comment]
Example url is 404.

**Comment by gerhat** [comment]
Changed the name of the example. New url is this: https://github.com/gerhat/material-ui-formik-components/blob/master/example/src/SimpleFormExample.jsx
