### ISSUE TITLE
Select component unable to get value from option if customize onChange

### ISSUE THREAD

**Issue by k8martian** [gerhat/material-ui-formik-components#7]
The Select field is empty if I use make custom onChange. Anyway to fix this? 

```
<Field
	name="name"
	label="label"
	component={Select}
	options={this.state.options}
	onChange={(e)=>{
	        formik.setFieldValue('nameValue', true);
		formik.handleSubmit(e);
	}}
/>
```

also I get this warning

> Warning: Failed prop type: The prop `value` is marked as required in `SelectInput`, but its value is `undefined`.

**Comment by k8martian** [comment]
i removed handleSubmit the value is now display, and setting initialValues and remove the warning.

**Comment by gerhat** [comment]
@k8martian glad you solved it! Thanks for using material-ui-formik-components.
