### ISSUE TITLE
Update documentation so developers know how to directly import

### ISSUE THREAD

**Issue by pmacom** [gerhat/material-ui-formik-components#8]
Our project doesn't plan on using the date picker at any point. (I kind of think it's ugly tbh). If a developer is importing  like

```
import { TextField, Select } from "material-ui-formik-components";
```

The compiler will complain about not having the material-ui-picker library. It should be mentioned that they can import like this as well.

```
import Select from "material-ui-formik-components/Select";
```

**Comment by gerhat** [comment]
@pmacom thanks a lot for your input. Both documentation and example have been updated.
How come `import Select from "material-ui-formik-components/Select";` works for you?

I had to write it with curly brackets like this:
`import { Select } from "material-ui-formik-components/Select";`

**Comment by pmacom** [comment]
You're right. Sorry for the mixup. 👍
